language: node_js
before_script:
  - npm install -g gulp
script: gulp build
deploy:
  provider: pages:git
  script: npm run deploy
  cleanup: true
  keep_history: true
  strategy: git
  local_dir: dist
  edge: true
  on:
    branch: master